const categories = [
  {
    id: 621,
    parent_id: 2,
    name: 'living',
    is_active: true,
    position: 11,
    level: 2,
    product_count: 480879,
    children_data: [
      {
        id: 166,
        parent_id: 621,
        name: 'sofas',
        is_active: true,
        position: 1,
        level: 3,
        product_count: 108315,
        children_data: [],
      },
      {
        id: 145,
        parent_id: 621,
        name: 'sectionals',
        is_active: true,
        position: 2,
        level: 3,
        product_count: 129786,
        children_data: [],
      },
      {
        id: 193,
        parent_id: 621,
        name: 'sleeper sofas',
        is_active: true,
        position: 3,
        level: 3,
        product_count: 2048,
        children_data: [],
      },
      {
        id: 167,
        parent_id: 621,
        name: 'chairs',
        is_active: true,
        position: 4,
        level: 3,
        product_count: 48898,
        children_data: [],
      },
      {
        id: 601,
        parent_id: 621,
        name: 'recliners',
        is_active: true,
        position: 5,
        level: 3,
        product_count: 381,
        children_data: [],
      },
      {
        id: 168,
        parent_id: 621,
        name: 'chaise lounges',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 7675,
        children_data: [],
      },
      {
        id: 169,
        parent_id: 621,
        name: 'ottomans + stools',
        is_active: true,
        position: 7,
        level: 3,
        product_count: 29692,
        children_data: [],
      },
      {
        id: 170,
        parent_id: 621,
        name: 'coffee tables',
        is_active: true,
        position: 8,
        level: 3,
        product_count: 39633,
        children_data: [],
      },
      {
        id: 197,
        parent_id: 621,
        name: 'end tables',
        is_active: true,
        position: 9,
        level: 3,
        product_count: 17471,
        children_data: [],
      },
      {
        id: 196,
        parent_id: 621,
        name: 'console tables',
        is_active: true,
        position: 10,
        level: 3,
        product_count: 5180,
        children_data: [],
      },
      {
        id: 623,
        parent_id: 621,
        name: 'sideboards',
        is_active: true,
        position: 11,
        level: 3,
        product_count: 56602,
        children_data: [],
      },
      {
        id: 172,
        parent_id: 621,
        name: 'bookshelves',
        is_active: true,
        position: 12,
        level: 3,
        product_count: 5990,
        children_data: [],
      },
      {
        id: 194,
        parent_id: 621,
        name: 'tv stands',
        is_active: true,
        position: 13,
        level: 3,
        product_count: 17319,
        children_data: [],
      },
      {
        id: 173,
        parent_id: 621,
        name: 'wall units',
        is_active: true,
        position: 14,
        level: 3,
        product_count: 14684,
        children_data: [],
      },
      {
        id: 629,
        parent_id: 621,
        name: 'hallway units',
        is_active: true,
        position: 15,
        level: 3,
        product_count: 157,
        children_data: [],
      },
    ],
  },
  {
    id: 163,
    parent_id: 2,
    name: 'dining',
    is_active: true,
    position: 21,
    level: 2,
    product_count: 268385,
    children_data: [
      {
        id: 147,
        parent_id: 163,
        name: 'dining tables',
        is_active: true,
        position: 10,
        level: 3,
        product_count: 68724,
        children_data: [],
      },
      {
        id: 618,
        parent_id: 163,
        name: 'kitchen tables',
        is_active: true,
        position: 11,
        level: 3,
        product_count: 8350,
        children_data: [],
      },
      {
        id: 148,
        parent_id: 163,
        name: 'dining chairs',
        is_active: true,
        position: 31,
        level: 3,
        product_count: 99403,
        children_data: [],
      },
      {
        id: 613,
        parent_id: 163,
        name: 'benches',
        is_active: true,
        position: 32,
        level: 3,
        product_count: 2404,
        children_data: [],
      },
      {
        id: 149,
        parent_id: 163,
        name: 'buffets + sideboards',
        is_active: true,
        position: 42,
        level: 3,
        product_count: 60077,
        children_data: [],
      },
      {
        id: 150,
        parent_id: 163,
        name: 'display cabinets',
        is_active: true,
        position: 53,
        level: 3,
        product_count: 1500,
        children_data: [],
      },
      {
        id: 198,
        parent_id: 163,
        name: 'bar + counter stools',
        is_active: true,
        position: 55,
        level: 3,
        product_count: 31202,
        children_data: [],
      },
      {
        id: 203,
        parent_id: 163,
        name: 'bar cabinets + carts',
        is_active: true,
        position: 65,
        level: 3,
        product_count: 187,
        children_data: [],
      },
      {
        id: 600,
        parent_id: 163,
        name: 'bar + counter tables',
        is_active: true,
        position: 66,
        level: 3,
        product_count: 2238,
        children_data: [],
      },
    ],
  },
  {
    id: 152,
    parent_id: 2,
    name: 'bedroom',
    is_active: true,
    position: 31,
    level: 2,
    product_count: 171153,
    children_data: [
      {
        id: 154,
        parent_id: 152,
        name: 'beds',
        is_active: true,
        position: 10,
        level: 3,
        product_count: 82600,
        children_data: [],
      },
      {
        id: 211,
        parent_id: 152,
        name: 'mattresses',
        is_active: true,
        position: 11,
        level: 3,
        product_count: 90,
        children_data: [],
      },
      {
        id: 155,
        parent_id: 152,
        name: 'nightstands',
        is_active: true,
        position: 70,
        level: 3,
        product_count: 29296,
        children_data: [],
      },
      {
        id: 156,
        parent_id: 152,
        name: 'dressers',
        is_active: true,
        position: 80,
        level: 3,
        product_count: 24104,
        children_data: [],
      },
      {
        id: 158,
        parent_id: 152,
        name: 'chests',
        is_active: true,
        position: 99,
        level: 3,
        product_count: 8645,
        children_data: [],
      },
      {
        id: 616,
        parent_id: 152,
        name: 'vanity tables + desks',
        is_active: true,
        position: 100,
        level: 3,
        product_count: 1328,
        children_data: [],
      },
      {
        id: 201,
        parent_id: 152,
        name: 'poufs + stools',
        is_active: true,
        position: 101,
        level: 3,
        product_count: 17829,
        children_data: [],
      },
      {
        id: 614,
        parent_id: 152,
        name: 'benches',
        is_active: true,
        position: 103,
        level: 3,
        product_count: 7651,
        children_data: [],
      },
    ],
  },
  {
    id: 143,
    parent_id: 2,
    name: 'office',
    is_active: true,
    position: 32,
    level: 2,
    product_count: 25871,
    children_data: [
      {
        id: 142,
        parent_id: 143,
        name: 'office desks',
        is_active: true,
        position: 19,
        level: 3,
        product_count: 2620,
        children_data: [],
      },
      {
        id: 141,
        parent_id: 143,
        name: 'office chairs',
        is_active: true,
        position: 29,
        level: 3,
        product_count: 13441,
        children_data: [],
      },
      {
        id: 605,
        parent_id: 143,
        name: 'file cabinets',
        is_active: true,
        position: 30,
        level: 3,
        product_count: 105,
        children_data: [],
      },
      {
        id: 610,
        parent_id: 143,
        name: 'credenzas',
        is_active: true,
        position: 31,
        level: 3,
        product_count: 433,
        children_data: [],
      },
      {
        id: 140,
        parent_id: 143,
        name: 'bookcases',
        is_active: true,
        position: 41,
        level: 3,
        product_count: 6765,
        children_data: [],
      },
      {
        id: 620,
        parent_id: 143,
        name: 'conference tables',
        is_active: true,
        position: 42,
        level: 3,
        product_count: 1055,
        children_data: [],
      },
      {
        id: 213,
        parent_id: 143,
        name: 'reception desks',
        is_active: true,
        position: 43,
        level: 3,
        product_count: 91,
        children_data: [],
      },
      {
        id: 628,
        parent_id: 143,
        name: 'workstations',
        is_active: true,
        position: 44,
        level: 3,
        product_count: 1362,
        children_data: [],
      },
    ],
  },
  {
    id: 139,
    parent_id: 2,
    name: 'lighting',
    is_active: true,
    position: 33,
    level: 2,
    product_count: 3259,
    children_data: [
      {
        id: 606,
        parent_id: 139,
        name: 'ceiling lights',
        is_active: true,
        position: 1,
        level: 3,
        product_count: 1884,
        children_data: [],
      },
      {
        id: 208,
        parent_id: 139,
        name: 'wall sconces',
        is_active: true,
        position: 14,
        level: 3,
        product_count: 294,
        children_data: [],
      },
      {
        id: 205,
        parent_id: 139,
        name: 'floor lamps',
        is_active: true,
        position: 24,
        level: 3,
        product_count: 507,
        children_data: [],
      },
      {
        id: 206,
        parent_id: 139,
        name: 'table lamps',
        is_active: true,
        position: 34,
        level: 3,
        product_count: 657,
        children_data: [],
      },
    ],
  },
  {
    id: 160,
    parent_id: 2,
    name: 'decor',
    is_active: true,
    position: 34,
    level: 2,
    product_count: 24275,
    children_data: [
      {
        id: 612,
        parent_id: 160,
        name: 'mirrors',
        is_active: true,
        position: 1,
        level: 3,
        product_count: 5068,
        children_data: [],
      },
      {
        id: 609,
        parent_id: 160,
        name: 'clocks',
        is_active: true,
        position: 21,
        level: 3,
        product_count: 412,
        children_data: [],
      },
      {
        id: 204,
        parent_id: 160,
        name: 'rugs',
        is_active: true,
        position: 22,
        level: 3,
        product_count: 204,
        children_data: [],
      },
      {
        id: 209,
        parent_id: 160,
        name: 'magazine racks',
        is_active: true,
        position: 32,
        level: 3,
        product_count: 517,
        children_data: [],
      },
      {
        id: 210,
        parent_id: 160,
        name: 'vases + planters',
        is_active: true,
        position: 51,
        level: 3,
        product_count: 714,
        children_data: [],
      },
      {
        id: 617,
        parent_id: 160,
        name: 'shelves',
        is_active: true,
        position: 52,
        level: 3,
        product_count: 1517,
        children_data: [],
      },
      {
        id: 202,
        parent_id: 160,
        name: 'coat racks',
        is_active: true,
        position: 53,
        level: 3,
        product_count: 752,
        children_data: [],
      },
      {
        id: 619,
        parent_id: 160,
        name: 'umbrella stands',
        is_active: true,
        position: 54,
        level: 3,
        product_count: 16,
        children_data: [],
      },
      {
        id: 627,
        parent_id: 160,
        name: 'wallpaper',
        is_active: true,
        position: 55,
        level: 3,
        product_count: 2149,
        children_data: [],
      },
      {
        id: 630,
        parent_id: 160,
        name: 'accent pillows',
        is_active: true,
        position: 56,
        level: 3,
        product_count: 11706,
        children_data: [],
      },
    ],
  },
  {
    id: 162,
    parent_id: 2,
    name: 'outdoor',
    is_active: true,
    position: 35,
    level: 2,
    product_count: 7667,
    children_data: [
      {
        id: 189,
        parent_id: 162,
        name: 'outdoor dining tables',
        is_active: true,
        position: 28,
        level: 3,
        product_count: 1319,
        children_data: [],
      },
      {
        id: 188,
        parent_id: 162,
        name: 'outdoor dining chairs',
        is_active: true,
        position: 29,
        level: 3,
        product_count: 707,
        children_data: [],
      },
      {
        id: 190,
        parent_id: 162,
        name: 'outdoor sofas',
        is_active: true,
        position: 59,
        level: 3,
        product_count: 1696,
        children_data: [],
      },
      {
        id: 191,
        parent_id: 162,
        name: 'outdoor sectionals',
        is_active: true,
        position: 69,
        level: 3,
        product_count: 527,
        children_data: [],
      },
      {
        id: 603,
        parent_id: 162,
        name: 'outdoor chaise lounges',
        is_active: true,
        position: 70,
        level: 3,
        product_count: 1162,
        children_data: [],
      },
      {
        id: 183,
        parent_id: 162,
        name: 'outdoor chairs',
        is_active: true,
        position: 71,
        level: 3,
        product_count: 406,
        children_data: [],
      },
      {
        id: 192,
        parent_id: 162,
        name: 'outdoor coffee tables',
        is_active: true,
        position: 72,
        level: 3,
        product_count: 548,
        children_data: [],
      },
      {
        id: 604,
        parent_id: 162,
        name: 'outdoor end tables',
        is_active: true,
        position: 73,
        level: 3,
        product_count: 182,
        children_data: [],
      },
      {
        id: 631,
        parent_id: 162,
        name: 'outdoor vases + planters',
        is_active: true,
        position: 74,
        level: 3,
        product_count: 641,
        children_data: [],
      },
      {
        id: 633,
        parent_id: 162,
        name: 'outdoor poufs + stools',
        is_active: true,
        position: 75,
        level: 3,
        product_count: 173,
        children_data: [],
      },
      {
        id: 634,
        parent_id: 162,
        name: 'outdoor bar + counter stools',
        is_active: true,
        position: 76,
        level: 3,
        product_count: 265,
        children_data: [],
      },
      {
        id: 635,
        parent_id: 162,
        name: 'outdoor benches',
        is_active: true,
        position: 77,
        level: 3,
        product_count: 64,
        children_data: [],
      },
    ],
  },
  {
    id: 199,
    parent_id: 2,
    name: 'sale',
    is_active: true,
    position: 1001,
    level: 2,
    product_count: 373,
    children_data: [
      {
        id: 626,
        parent_id: 199,
        name: 'special promotions',
        is_active: true,
        position: 1,
        level: 3,
        product_count: 81,
        children_data: [],
      },
      {
        id: 625,
        parent_id: 199,
        name: 'showroom displays',
        is_active: true,
        position: 2,
        level: 3,
        product_count: 245,
        children_data: [],
      },
      {
        id: 637,
        parent_id: 199,
        name: 'ready-to-ship savings',
        is_active: false,
        position: 3,
        level: 3,
        product_count: 125,
        children_data: [],
      },
    ],
  },
  {
    id: 624,
    parent_id: 2,
    name: 'parts',
    is_active: true,
    position: 1003,
    level: 2,
    product_count: 9769,
    children_data: [],
  },
  {
    id: 636,
    parent_id: 2,
    name: 'excluded from discount',
    is_active: false,
    position: 1004,
    level: 2,
    product_count: 108,
    children_data: [],
  },
]

const parsedCategories = categories
  .map((category) => {
    const { name: parentName, children_data: children } = category
    const parsedChildren = children.map((subCategory) => {
      const { id, name } = subCategory
      return {
        id,
        value: id,
        label: `${parentName}: ${name}`,
        // description: `${name}`,
        parent: parentName,
      }
    })

    return parsedChildren
  })
  .flat()

export default [
  { value: 0, label: 'Select Category', parent: '' },
  ...parsedCategories,
]
// export default parsedCategories
